# .streamlit/secrets.toml

[firebaseConfig]
apiKey = "AIzaSyDPdjXqwX_MwiCGccsmK1UCdrbZSHwQHQo"
authDomain = "intergalacticpro-ai.firebaseapp.com"
databaseURL = "https://intergalacticpro-ai-default-rtdb.firebaseio.com"
projectId = "intergalacticpro-ai"
storageBucket = "intergalacticpro-ai.appspot.com"
messagingSenderId = "486968289811"
appId = "1:486968289811:web:4b151ba5cb53ec1a9aede6"
measurementId = "G-8N5092ZXF9"
